### ISSUE TITLE
suggestion: add tree of contents to the analysis

### ISSUE THREAD

**Issue by romunov** [surajvv12/17_Classification#1]
I would suggest adding a tree of content to the analysis.

```
output:
  html_document:
    toc: true
    toc_depth: 1
```
